# Generated by Django 4.0.4 on 2022-06-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeniden_app', '0003_alter_message_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='what_is_İt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
